package com.revature.problem;

/*
 Java/.NET/Python
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.

 */

public class Fib {

	public int calc() {
		int f = 1;
		int s = 0;
		int t = 0;
		int result = 0;

		for (int x = 0; t < 4000000; x++) {

			System.out.println(" x: " + x + "....t: " + t);

			t = f + s;
			f = s;
			s = t;

			if (t % 2 == 0) {
				result += t;	
			}
		}
System.out.println("result:  "+result);
		return result;
	}
}
